In [1]:
!pip install numpy

In [4]:
import numpy as np

## Create array using numpy
## Create a ID array
arr1=np.array([1,2,3,4,5,6])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5 6]
<class 'numpy.ndarray'>
(6,)


In [7]:
arr2 = np.array([1,2,3,4,5])
arr2.reshape(1,5)

array([[1, 2, 3, 4, 5]])

In [9]:
## 2 dimension array

arr2 = np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])
print(arr2)
print(arr2.shape)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
(2, 6)


In [12]:
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [14]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [15]:
## identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [18]:
arr = np.array([[1,2,3,4],[4,3,2,1]])
print(arr)
arr.reshape(4,2)

[[1 2 3 4]
 [4 3 2 1]]


array([[1, 2],
       [3, 4],
       [4, 3],
       [2, 1]])

In [ ]:
## Attributes on numpy
arr = np.array([[1,2,3],[4,5,6]])

print("Array:\n", arr)
print("shape\n", arr.shape) # Output: (2,3)
print("Number of Dimension\n", arr.ndim) # Output: 2
print("Size (Number of elements):", arr.size) # Output: 6
print("Data type:", arr.dtype) # Output: int64 (may vary based on platform)
print("Item size(in bytes)", arr.itemsize) # Output: 8 (may vary based on)


Array:
 [[1 2 3]
 [4 5 6]]
shape
 (2, 3)
Number of Dimension
 2
Size (Number of elements): 6
Data type: int64
Item size(in bytes) 8


In [22]:
### Numpy Vectorized Operation
arr1=np.array([1,2,3,4,5])
arr2=np.array([10,11,12,13,14])

### Element Wise addition
print("Addition:", arr1+arr2)

### Element wise subtraction
print("Substraction", arr1-arr2)

### Element-wise multiplication
print("Multiplication", arr1*arr2)

### Element-wise Division
print("Division", arr1/arr2)

Addition: [11 13 15 17 19]
Substraction [-9 -9 -9 -9 -9]
Multiplication [10 22 36 52 70]
Division [0.1        0.18181818 0.25       0.30769231 0.35714286]


In [24]:
## Universal Function
arr = np.array([2,3,4,5,6])

## Square root
print(np.sqrt(arr))

## Exponetial
print(np.exp(arr))

## Sine
print(np.sin(arr))

## Natural Log
print(np.log(arr))



[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [25]:
## Array slicing and Indexing

arr = np.array([[1,2,3,4,],[5,6,7,8],[9,10,11,12]])
print("Array : \n", arr)

Array : 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
print(arr[:2,:2])


[[1 2]
 [5 6]]


In [29]:
## Modify array elements
arr[0,0]=100
print(arr)

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [30]:
arr[1:]=100
print(arr)

[[100   2   3   4]
 [100 100 100 100]
 [100 100 100 100]]


In [31]:
### Statistical concepts
## to have a mean  of 0 and standard deviation of 1
data = np.array([1,2,3,4,5])
std_dev = np.std(data)

# Calculate the mean and standard deviation
mean = np.mean(data)
std_dev = np.std(data)

# Standardized the data
standardized_data = (data-mean)/std_dev
print("Standardized data:",standardized_data)

Standardized data: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [32]:
data = np.array([1,2,3,4,5,6,7,8,9,10])

# Mean
mean = np.mean(data)
print("Mean:", mean)

# Median
median = np.median(data)
print("Median:", median)

# Standard Deviation
std_dev = np.std(data)
print("Standard deviation:", std_dev)

# Variance
variance = np.var(data)
print("Variance", variance)



Mean: 5.5
Median: 5.5
Standard deviation: 2.8722813232690143
Variance 8.25


In [34]:
## Logical operation
data = np.array([1,2,3,4,5,6,7,8,9,10])

data[(data>5) & (data<9)]

array([6, 7, 8])