# Module: NumPy Assignments
## Lesson: NumPy
### Assignment 1: Array Creation and Manipulation

1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.

In [2]:
import pandas as pd
import numpy as np

np_arr = np.random.randint(1,21,size=(5,5))
print("Original Array: ")
print(np_arr)

np_arr[:,2] =1
print("third column replaced with all 1:")
print(np_arr)

Original Array: 
[[16  4  1  9  4]
 [17 14  8 16  8]
 [17 11  1 16  3]
 [12 19  6  8 10]
 [ 7  3 12 12  8]]
third column replaced with all 1:
[[16  4  1  9  4]
 [17 14  1 16  8]
 [17 11  1 16  3]
 [12 19  1  8 10]
 [ 7  3  1 12  8]]


2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

In [4]:
array = np.random.randint(1,17,size=(4,4))
print("Original array:")
print(array)

print("Diagonal 0 array")
np.fill_diagonal(array,0)
print(array)


Original array:
[[ 5  7  2  8]
 [11 12 10 13]
 [ 2  7  5  3]
 [15  1 12 13]]
Diagonal 0 array
[[ 0  7  2  8]
 [11  0 10 13]
 [ 2  7  0  3]
 [15  1 12  0]]


### Assignment 2: Array Indexing and Slicing

1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.

In [9]:
array = np.arange(1,37).reshape((6,6))
print("Original Array:")
print(array)

sub = array[2:5,1:4]
print("sub array:")
print(sub)

Original Array:
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]
sub array:
[[14 15 16]
 [20 21 22]
 [26 27 28]]


2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

In [14]:
array = np.random.randint(1,100,size=(5,5))
print("Original array:")
print(array)

border_arr = np.concatenate((array[0,:],array[-1,:],array[1:-1,0],array[-1:1,-1]))
print("Border Array:")
print(border_arr)

Original array:
[[82 12 54 41  5]
 [57 18 22 86 77]
 [12 89 89 18 44]
 [71 67 97 31 47]
 [63 11 66 73 79]]
Border Array:
[82 12 54 41  5 63 11 66 73 79 57 12 71]


### Assignment 3: Array Operations

1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.

In [16]:
arr1 = np.random.randint(1,10,size=(3,4))
arr2 = np.random.randint(1,10,size=(3,4))
print("array 1")
print(arr1)
print()
print("array 2")
print(arr2)

print("perform element-wise addition,subtraction,multiplication,and division")
addition = arr1 + arr2
subtraction = arr1-arr2
multiplication = arr1*arr2
division = arr1/arr2

print(addition)
print(subtraction)
print(multiplication)
print(division)

array 1
[[1 7 5 3]
 [7 9 8 8]
 [7 8 2 4]]

array 2
[[3 6 1 3]
 [9 7 3 2]
 [2 9 6 3]]
perform element-wise addition,subtraction,multiplication,and division
[[ 4 13  6  6]
 [16 16 11 10]
 [ 9 17  8  7]]
[[-2  1  4  0]
 [-2  2  5  6]
 [ 5 -1 -4  1]]
[[ 3 42  5  9]
 [63 63 24 16]
 [14 72 12 12]]
[[0.33333333 1.16666667 5.         1.        ]
 [0.77777778 1.28571429 2.66666667 4.        ]
 [3.5        0.88888889 0.33333333 1.33333333]]


2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

In [18]:
arr = np.arange(1,17).reshape((4,4))
print("Original Array:")
print(arr)

print("Column-wise sum")
print(arr.sum(axis=0))
print("Row-Wise sum:")
print(arr.sum(axis=1))

Original Array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Column-wise sum
[28 32 36 40]
Row-Wise sum:
[10 26 42 58]


### Assignment 4: Statistical Operations

1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.

In [ ]:
arr = np.random.randint(1,100,size=(5,5))
print("Original array:")
print(arr)
print(f"Mean of array: {arr.mean()}")
print(f"Median of Array: {np.median(arr)}")
print(f"Variance of array: {np.var(arr)}")
print(f"Standard Deviation of array: {np.std(arr)}")

Original array:
[[91 31 44 23 96]
 [66 31 87 15 76]
 [60  7 81 85  4]
 [74 97 49 24 74]
 [94 44 25 91 60]]
Mean of array: 57.16
Median of Array: 60.0
Variance of array: 887.8144000000002
Standard Deviation of array: 29.796214524667395


2. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).

In [29]:
arr = np.arange(1,10).reshape((3,3))
print("Original array:")
print(arr)
print()

mean = np.mean(arr)
stdev = np.std(arr)
standardized_arr = (arr-mean)/stdev

print("Standardized Array:")
print(standardized_arr)

Original array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Standardized Array:
[[-1.54919334 -1.161895   -0.77459667]
 [-0.38729833  0.          0.38729833]
 [ 0.77459667  1.161895    1.54919334]]


### Assignment 5: Broadcasting

1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.

In [35]:
array = np.random.randint(1,11,size=(3,3))
row_array = np.random.randint(1,11,size=(3,))
print("Original Array:")
print(array)
print("1D Array:")
print(row_array)

result = array + row_array
print("Resulting array:")
print(result)

Original Array:
[[ 6  9  8]
 [ 7  7  6]
 [ 7  6 10]]
1D Array:
[4 2 5]
Resulting array:
[[10 11 13]
 [11  9 11]
 [11  8 15]]


2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.

In [41]:
array = np.random.randint(1,11,size=(4,4))
subtractor = np.random.randint(1,11,size=(4,))
print("Original array:")
print(array)
print("Subtractor:")
print(subtractor)

print("Original array after getting subtract:")
print(array-subtractor)

Original array:
[[ 7 10  6  9]
 [ 9 10  8  1]
 [ 6  3  3  3]
 [ 7  1  9 10]]
Subtractor:
[5 2 3 8]
Original array after getting subtract:
[[ 2  8  3  1]
 [ 4  8  5 -7]
 [ 1  1  0 -5]
 [ 2 -1  6  2]]


### Assignment 6: Linear Algebra

1. Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.

In [64]:
arrays = np.random.randint(1,11,size=(3,3))
print("Original Matrix")
print(arrays)

#calculate determinant
det = np.linalg.det(arrays)
print(f"Determinan: {det}")

inverse = np.linalg.inv(arrays)
print(f"Invers: {inverse}")

eigenvalues = np.linalg.eigvals(arrays)
print(f"Eigen Values: {eigenvalues}")

Original Matrix
[[ 6  7  5]
 [ 2  6  2]
 [10  1  5]]
Determinan: -52.00000000000001
Invers: [[-0.53846154  0.57692308  0.30769231]
 [-0.19230769  0.38461538  0.03846154]
 [ 1.11538462 -1.23076923 -0.42307692]]
Eigen Values: [14.72237586 -1.05867093  3.33629507]


2. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.

In [69]:
arr1 = np.random.randint(1,11,size=(2,3))
arr2 = np.random.randint(1,11,size=(3,2))

print(arr1)
print()
print(arr2)
print()

print("arr1 times arr2:")
print(np.dot(arr1,arr2))


[[4 9 1]
 [3 5 7]]

[[6 4]
 [8 3]
 [9 6]]

arr1 times arr2:
[[105  49]
 [121  69]]


### Assignment 7: Advanced Array Manipulation

1. Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).

In [ ]:
array = np.arange(1,10).reshape(3,3)
print(array)
print(array.reshape(1,9))
print(array.reshape(9,1))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3 4 5 6 7 8 9]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


2. Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5).

In [78]:
arrays = np.random.randint(1,11,size=(5,5))
print(arrays)
print(arrays.reshape(1,25))
print(arrays.flatten())
print(arrays.reshape(5,5))

[[ 5  7  4  9  5]
 [ 9  7  6  6  2]
 [ 5  2  2  7  5]
 [ 8  2  8  1  9]
 [ 2  8  5 10  2]]
[[ 5  7  4  9  5  9  7  6  6  2  5  2  2  7  5  8  2  8  1  9  2  8  5 10
   2]]
[ 5  7  4  9  5  9  7  6  6  2  5  2  2  7  5  8  2  8  1  9  2  8  5 10
  2]
[[ 5  7  4  9  5]
 [ 9  7  6  6  2]
 [ 5  2  2  7  5]
 [ 8  2  8  1  9]
 [ 2  8  5 10  2]]


### Assignment 8: Fancy Indexing and Boolean Indexing

1. Create a NumPy array of shape (5, 5) filled with random integers. Use fancy indexing to extract the elements at the corners of the array.

In [91]:
arr = np.random.randint(1,11,size=(5,5))
print("Original Array:")
print(arr)

# fancy indexing
corners = arr[[0,0,-1,-1],[0,-1,0,-1]]
print("Corner elements:")
print(corners)


Original Array:
[[10 10  8  1  1]
 [ 1  7  6  3  8]
 [ 2  8  6  5  7]
 [ 9  4 10  8  4]
 [ 9  4  2 10  2]]
Corner elements:
[10  1  9  2]


2. Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing to set all elements greater than 10 to 10.

In [92]:
array = np.random.randint(1,21,size=(4,4))
print("Original array:")
print(array)

array[array>10] = 10
print("Mofied Array:")
print(array)

Original array:
[[18 20  9 20]
 [ 1  3  5  8]
 [17  3 15 20]
 [11 16  1  2]]
Mofied Array:
[[10 10  9 10]
 [ 1  3  5  8]
 [10  3 10 10]
 [10 10  1  2]]


### Assignment 9: Structured Arrays

1. Create a structured array with fields 'name' (string), 'age' (integer), and 'weight' (float). Add some data and sort the array by age.

In [ ]:
data_type = [('name','U10'),('age','i4'),('weight','f4')]
data = np.array([('Alice',25,55.5),('Bob',30,85.3),('Charlie',20,65.2)],dtype=data_type)
print("Original array:")
print(data)

# Sort the array by age
sorted_data = np.sort(data,order='age')
print("Sorted array by age:")
print(sorted_data)

Original array:
[('Alice', 25, 55.5) ('Bob', 30, 85.3) ('Charlie', 20, 65.2)]
Sorted array by age:
[('Charlie', 20, 65.2) ('Alice', 25, 55.5) ('Bob', 30, 85.3)]


2. Create a structured array with fields 'x' and 'y' (both integers). Add some data and compute the Euclidean distance between each pair of points.

In [96]:
data_type = [('x','i4'),('y','i4')]
data = np.array([(1,2),(3,4),(5,6)], dtype=data_type)
print("Original array:")
print(data)

distance = np.sqrt((data['x'][:,np.newaxis] - data['x'])**2 + (data['y'][:,np.newaxis] - data['y'])**2)
print("Euclidean distances:")
print(distance)

Original array:
[(1, 2) (3, 4) (5, 6)]
Euclidean distances:
[[0.         2.82842712 5.65685425]
 [2.82842712 0.         2.82842712]
 [5.65685425 2.82842712 0.        ]]


### Assignment 10: Masked Arrays

1. Create a masked array of shape (4, 4) with random integers and mask the elements greater than 10. Compute the sum of the unmasked elements.

In [98]:
import numpy.ma as ma

# Create a masked array of shape (4,4) with random integers
array = np.random.randint(1, 21, size=(4,4))
masked_array = ma.masked_greater(array,10)
print("Original array:")
print(array)
print("masked array:")
print(masked_array)

# Compute the sum od the unmasked elements
sum_unmasked = masked_array.sum()
print("Sum of the unmasked elements:", sum_unmasked)

Original array:
[[20 16 10 12]
 [ 5 11  5 16]
 [17 15 12 20]
 [11  3 11 16]]
masked array:
[[-- -- 10 --]
 [5 -- 5 --]
 [-- -- -- --]
 [-- 3 -- --]]
Sum of the unmasked elements: 23


2. Create a masked array of shape (3, 3) with random integers and mask the diagonal elements. Replace the masked elements with the mean of the unmasked elements.

In [102]:
array = np.random.randint(1,21,size=(3,3))
masked_array = ma.masked_array(array,mask=np.eye(3,dtype=bool))
print("Original Array:")
print(array)
print("masked array:")
print(masked_array)

# Replace the masked elements with the mean of the unmasked array
mean_unmasked = masked_array.mean()
masked_array = masked_array.filled(mean_unmasked)
print("Modified masked array:")
print(masked_array)

Original Array:
[[14  9 15]
 [20 17  9]
 [17  2 14]]
masked array:
[[-- 9 15]
 [20 -- 9]
 [17 2 --]]
Modified masked array:
[[12  9 15]
 [20 12  9]
 [17  2 12]]
